apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
spec:
  replicas: 2
  selector:
    app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/db
        ports:
        - containerPort: 27017
          protocol: TCP
      volumes:
        - name: mongodb-data
          hostPath:
            path: /tmp/mongodb